# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /posts/:year/:month/:day/:title

# Setup
title:            '坤平的主页'
tagline:          'ipaler.github.io'
keywords:		  'ipaler.github.io,github,blog,jekyll,open'
description:      'ipaler.github.io,This is personal site of ipaler'
url:              'https://ipaler.github.io'
baseurl:          ''

# Navigation
navigation:
- text: 博文搜索
  url: /search/
- text: 文章列表
  url : /archive/
- text: 我的标签
  url: /tags/
- text: 我的简历
  url: /resume/
- text: 有关于我
  url: /about/

# Author Details
author:         '坤平'
github:         'https://github.com/ipaler'
linkedin:       'https://ae.linkedin.com/in/ipaler/'
twitter:        'https://twitter.com/ipaler'
facebook:       'https://www.facebook.com/ipaler'
gplus:          'https://plus.google.com/100425/'

# Google Analytics
gahandler: 'UA-53220404-1'

# Disqus
disqushandler: 'ipaler'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/posts/page:num'
destination: ./_site

# Custom vars
version:          0.1.10
